[package]
name = "KeePass"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
block-modes = "0.9.1"
rand = "0.9"
hex = "0.4"
rpassword = "7.2.0"
lazy_static = "1.4.0"
aes-gcm = "0.10.3"
argon2 = "0.5.3"
rusqlite = "0.33.0"
cursive = "0.21.1"
clipboard = "0.5.0"
